apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 'https://github.com/xpartla/pharmacy-webapi//deployments/kustomize/install'
  - openapi-ui.service.yaml
  - http-route.yaml

patches:
  - path: patches/pharmacy-webapi.deployment.yaml

labels:
  - pairs:
      wac-fiit.github.io/component: backend
