apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - http-route.yaml
  - webcomponent-link.yaml
  - webcomponent-content.yaml

labels:
  - pairs:
      app.kubernetes.io/component: mongo-express
